apiVersion: v1
kind: Secret
metadata:
  name: aws-config
type: Opaque
data:
  # Configuration values can be set as key-value properties
  aws_access_key_id: QVNJQVFKNUY0Mk1CWDQ3M0s1RVg= 
  aws_secret_access_key: b3ljNkg1ZGlLTms1azg5WThsTWFZSWxlaHREZmZ5bm0vMVhnSzhHTQ==

