apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    run: backend-user
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    service: backend-user