apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
  - name: "8080"
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    service: frontend
